---
version: 2
models:
- name: "observatory_reporting__obs__executive_scorecard"
  tags:
  - "prophecy_temp"
- name: "observatory_reporting__obs__leak_explainers"
  tags:
  - "prophecy_temp"
- name: "observatory_reporting__obs__leak_registry"
  tags:
  - "prophecy_temp"
- name: "observatory_reporting__obs__priority_actions"
  tags:
  - "prophecy_temp"
- name: "observatory_reporting__obs_exp_leak_definitions_from_000"
  tags:
  - "prophecy_temp"
- name: "observatory_reporting__obs_exp_leak_definitions_from_002"
  tags:
  - "prophecy_temp"
- name: "observatory_reporting__obs_exp_leak_definitions_from_003"
  tags:
  - "prophecy_temp"
- name: "observatory_reporting__obs_exp_leak_definitions_from_004"
  tags:
  - "prophecy_temp"
